//
//  GrocerySections.swift
//  Garugu_GroceryApp
//
//  Created by Garugu,Sai Shanmukh on 4/12/22.
//
import Foundation

struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Bread/Bakery",items_Array:
[GroceryItem(itemName:"sandwich loaves",itemImage:"SandwichLoaf",itemInfo:"A sandwich loaf is a stacked party entrée that looks like a cake. While rare today, the food was quite popular during the mid 20th century in the United States. To create a sandwich loaf, bread is cut horizontally and spread with layers of filling. Common fillings include egg salad, chicken salad, ham salad, tuna salad, and Cheez Whiz, but other fillings are possible, including peanut butter and jelly and mock egg salad made from tofu. In a simple sandwich loaf, the fillings may all be the same, but in more complex creations each layer is different."),
GroceryItem(itemName: "Cookies", itemImage: "cookie", itemInfo: "A cookie is a baked or cooked snack or dessert that is typically small, flat and sweet. It usually contains flour, sugar, egg, and some type of oil, fat, or butter. It may include other ingredients such as raisins, oats, chocolate chips, nuts, etc.In most English-speaking countries except for the United States, crunchy cookies are called biscuits. Many Canadians also use this term. Chewier biscuits are sometimes called cookies even in the United Kingdom. Some cookies may also be named by their shape, such as date squares or bars."),
GroceryItem(itemName: "Cake", itemImage: "cake", itemInfo: "Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations that can be simple or elaborate, and that share features with other desserts such as pastries, meringues, custards, and pies."),
GroceryItem(itemName: "Doughnut", itemImage: "donut", itemInfo: "A doughnut or donut is a type of food made from leavened fried dough. It is popular in many countries and is prepared in various forms as a sweet snack that can be homemade or purchased in bakeries, supermarkets, food stalls, and franchised specialty vendors. Doughnut is the traditional spelling, while donut is the simplified version; the terms are often used interchangeably."),
GroceryItem(itemName: "Muffin", itemImage: "muffin", itemInfo: "A muffin is an individually portioned baked product, however the term can refer to one of two distinct items: a part-raised flatbread (like a crumpet) that is baked and then cooked on a griddle (typically unsweetened), or an (often sweetened) quickbread (like a cupcake) that is chemically leavened and then baked in a mold.")] )

let groceryitem2 = Grocery( section: "Diary", items_Array: [
    GroceryItem(itemName: "Milk", itemImage: "milk", itemInfo: "Milk is a nutrient-rich liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals (including breastfed human infants) before they are able to digest solid food. Early-lactation milk, which is called colostrum, contains antibodies that strengthen the immune system, and thus reduces the risk of many diseases. Milk contains many other nutrients, including protein and lactose."),
    GroceryItem(itemName: "Yogurt", itemImage: "yogurt", itemInfo: "Yogurt also spelled yoghurt, yogourt or yoghourt, is a food produced by bacterial fermentation of milk. The bacteria used to make yogurt are known as yogurt cultures. Fermentation of sugars in the milk by these bacteria produces lactic acid, which acts on milk protein to give yogurt its texture and characteristic tart flavor. Cow's milk is the milk most commonly used to make yogurt. Milk from water buffalo, goats, ewes, mares, camels, and yaks are also used to produce yogurt. The milk used may be homogenized or not. It may be pasteurized or raw."),
    GroceryItem(itemName: "Cheese", itemImage: "cheese", itemInfo: "Cheese is a dairy product produced in wide ranges of flavors, textures and forms by coagulation of the milk protein casein. It comprises proteins and fat from milk, usually the milk of cows, buffalo, goats, or sheep. During production, the milk is usually acidified and the enzymes of either rennet or bacterial enzymes with similar activity are added to cause the casein to coagulate. The solid curds are then separated from the liquid whey and pressed into finished cheese. Some cheeses have aromatic molds on the rind, the outer layer, or throughout."),
    GroceryItem(itemName: "Butter", itemImage: "butter", itemInfo: "Butter is a dairy product made from the fat and protein components of churned cream. It is a semi-solid emulsion at room temperature, consisting of approximately 80% butterfat. It is used at room temperature as a spread, melted as a condiment, and used as an ingredient in baking, sauce making, pan frying, and other cooking procedures."),
    GroceryItem(itemName: "Sour Cream", itemImage: "sourcream", itemInfo: "Sour cream (in North American English, Australian English and New Zealand English) or soured cream (British English) is a dairy product obtained by fermenting regular cream with certain kinds of lactic acid bacteria. The bacterial culture, which is introduced either deliberately or naturally, sours and thickens the cream. Its name comes from the production of lactic acid by bacterial fermentation, which is called souring. Crème fraîche is one type of sour cream with a high fat content and less sour taste.")] )

let groceryitem3 = Grocery( section: "Spices", items_Array: [
    GroceryItem(itemName: "Cinnamon", itemImage: "cinnamon", itemInfo: "Cinnamon is a spice obtained from the inner bark of several tree species from the genus Cinnamomum. Cinnamon is used mainly as an aromatic condiment and flavouring additive in a wide variety of cuisines, sweet and savoury dishes, breakfast cereals, snackfoods, teas, and traditional foods. The aroma and flavour of cinnamon derive from its essential oil and principal component, cinnamaldehyde, as well as numerous other constituents including eugenol."),
    GroceryItem(itemName: "Cloves", itemImage: "cloves", itemInfo: "Cloves are the aromatic flower buds of a tree in the family Myrtaceae, Syzygium aromaticum. They are native to the Maluku Islands (or Moluccas) in Indonesia, and are commonly used as a spice. Cloves are available throughout the year owing to different harvest seasons in different countries."),
    GroceryItem(itemName: "Cumin", itemImage: "cumin", itemInfo: "Cumin or (Cuminum cyminum) is a flowering plant in the family Apiaceae, native to the Irano-Turanian Region. Its seeds – each one contained within a fruit, which is dried – are used in the cuisines of many cultures in both whole and ground form. Although cumin is thought to have uses in traditional medicine, there is no high-quality evidence that it is safe or effective as a therapeutic agent."),
    GroceryItem(itemName: "Garlic", itemImage: "garlic", itemInfo: "Garlic (Allium sativum) is a species of bulbous flowering plant in the genus Allium. Its close relatives include the onion, shallot, leek, chive, Welsh onion and Chinese onion. It is native to Central Asia and northeastern Iran and has long been used as a seasoning worldwide, with a history of several thousand years of human consumption and use. It was known to ancient Egyptians and has been used as both a food flavoring and a traditional medicine. China produces 76% of the world's supply of garlic."),
    GroceryItem(itemName: "Ginger", itemImage: "ginger", itemInfo: "Ginger (Zingiber officinale) is a flowering plant whose rhizome, ginger root or ginger, is widely used as a spice and a folk medicine. It is a herbaceous perennial which grows annual pseudostems (false stems made of the rolled bases of leaves) about one meter tall bearing narrow leaf blades. The inflorescences bear flowers having pale yellow petals with purple edges, and arise directly from the rhizome on separate shoots.")] )

let groceryitem4 = Grocery( section: "Beverages", items_Array: [
    GroceryItem(itemName: "Water", itemImage: "water", itemInfo: "Water is the most popular drink in the world. This is such a simple beverage, and yet no one can survive without it. This is why people have invented different water treatment systems, to ensure everyone around the world can have clean and safe water to drink."),
    GroceryItem(itemName: "Cola", itemImage: "cola", itemInfo: "Cola is a carbonated soft drink flavored with vanilla, cinnamon, citrus oils and other flavorings. Cola became popular worldwide after pharmacist John Pemberton invented Coca-Cola, a trademarked brand, in 1886, which was later imitated by other manufacturers. Most colas contain caffeine, which was originally sourced from the kola nut, leading to the drink's name, though other sources are now also used. The original cola drink by Pemberton contained an extract from the coca plant as well. His non-alcoholic recipe was inspired by the coca wine of pharmacist Angelo Mariani, created in 1863."),
    GroceryItem(itemName: "Lemonade", itemImage: "lemonade", itemInfo: "Lemonade is a sweetened lemon-flavored beverage. There are varieties of lemonade found throughout the world. In North America and South Asia, cloudy lemonade dominates. It is traditionally a homemade drink using lemon juice, water, and a sweetener such as cane sugar, simple syrup or honey. In the United Kingdom, Ireland, Central Europe and Australia, a carbonated lemonade is more common. Despite the differences between the drinks, each is known simply as lemonade in countries where it is dominant."),
    GroceryItem(itemName: "Orange juice", itemImage: "OJ", itemInfo: "Orange juice is a liquid extract of the orange tree fruit, produced by squeezing or reaming oranges. It comes in several different varieties, including blood orange, navel oranges, valencia orange, clementine, and tangerine. As well as variations in oranges used, some varieties include differing amounts of juice vesicles, known as pulp in American English, and (juicy) bits in British English. These vesicles contain the juice of the orange and can be left in or removed during the manufacturing process. How juicy these vesicles are depend upon many factors, such as species, variety, and season. In American English, the beverage name is often abbreviated as OJ."),
    GroceryItem(itemName: "Spruce beer", itemImage: "sprucebeer", itemInfo: "Spruce beer is a beverage flavored with the buds, needles, or essence of spruce trees. Spruce beer can refer to either alcoholic or non-alcoholic beverages.")] )

let groceryitem5 = Grocery( section: "Meat", items_Array: [
    GroceryItem(itemName: "Salmon", itemImage: "salmon", itemInfo: "Salmon (/ˈsæmən/) is the common name for several species of ray-finned fish in the family Salmonidae. Other fish in the same family include trout, char, grayling, and whitefish. Salmon are native to tributaries of the North Atlantic (genus Salmo) and Pacific Ocean (genus Oncorhynchus). Many species of salmon have been introduced into non-native environments such as the Great Lakes of North America and Patagonia in South America. Salmon are intensively farmed in many parts of the world."),
    GroceryItem(itemName: "Chicken", itemImage: "chicken", itemInfo: "Chicken is the most common type of poultry in the world.[1] Owing to the relative ease and low cost of raising chickens—in comparison to mammals such as cattle or hogs—chicken meat (commonly called just chicken) and chicken eggs have become prevalent in numerous cuisines."),
    GroceryItem(itemName: "Bacon", itemImage: "bacon", itemInfo: "Bacon is a type of salt-cured pork made from various cuts, typically the belly or less fatty parts of the back. It is eaten as a side dish (particularly in breakfasts), used as a central ingredient (e.g., the bacon, lettuce, and tomato sandwich (BLT), or as a flavouring or accent (as in bacon bits in a salad)."),
    GroceryItem(itemName: "Turkey", itemImage: "turkey", itemInfo: "Turkey meat, commonly referred to as just turkey, is the meat from turkeys, typically domesticated turkeys but also wild turkeys. It is a popular poultry dish, especially in North America, where it is traditionally consumed as part of culturally significant events such as Thanksgiving and Christmas, as well as in standard cuisine."),
    GroceryItem(itemName: "Lamb Chops", itemImage: "lambchops", itemInfo: "A meat chop is a cut of meat cut perpendicular to the spine, and usually containing a rib or riblet part of a vertebra and served as an individual portion. The most common kinds of meat chops are pork and lamb. A thin boneless chop, or one with only the rib bone, may be called a cutlet, though the difference is not always clear. The term chop is not usually used for beef, but a T-bone steak is essentially a loin chop, a rib steak and a rib cutlet. ")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]
